
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crash?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
  security:
    user.name: crash-admin
    user.password: 123456789
logging:
  level:
    # TRACE < DEBUG < INFO < WARN < ERROR
    root: INFO

jwt:
  secret-key: X3JlZ2lzdGVyX3Nlc3Npb25fc3VwZXJfc2VjcmV0X2tleV8=

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080